# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /post/:title.html

# Setup
title:            Craig McCaskill
tagline:          'Product Designer'
description:      "UX designer and product thinker. It's all about the experience."
url:              http://hyde.getpoole.com

author:
  name:           'Craig McCaskill'
  url:            https://twitter.com/craigmccaskill

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/craigmccaskill/hyde

collections:
- portfolio